"use client";
import { useEffect, useMemo, useState } from 'react';
import { Bell, ChevronRight, CircleDollarSign, GlassWater, LayoutDashboard, Package, Plus, Search, Settings, ShoppingCart, Sparkles, TrendingUp, Wine, X, Save } from 'lucide-react';

type Recipe={id:string;name:string;category:string;cost:number;price:number;stock:string;ingredients:string};
type Ingredient={id:string;name:string;unit:string;quantity:number;min:number;price:number};
const seedRecipes:Recipe[]=[
{id:'margarita',name:'Margarita',category:'Classic',cost:1.82,price:9.5,stock:'OK',ingredients:'Tequila · Triple sec · Lima'},
{id:'mojito',name:'Mojito',category:'Classic',cost:1.46,price:9,stock:'OK',ingredients:'Ron · Lima · Hierbabuena · Soda'},
{id:'negroni',name:'Negroni',category:'Classic',cost:2.35,price:11,stock:'Bajo',ingredients:'Gin · Campari · Vermut rojo'},
{id:'daiquiri',name:'Daiquiri',category:'Sour',cost:1.31,price:8.5,stock:'OK',ingredients:'Ron · Lima · Azúcar'}];
const seedIngredients:Ingredient[]=[
{id:'campari',name:'Campari',unit:'L',quantity:.42,min:1,price:18},{id:'hierbabuena',name:'Hierbabuena',unit:'g',quantity:180,min:250,price:.03},{id:'triple-sec',name:'Triple sec',unit:'L',quantity:.7,min:1,price:16},{id:'tequila',name:'Tequila',unit:'L',quantity:2.4,min:1,price:22},{id:'ron',name:'Ron',unit:'L',quantity:3.2,min:1,price:15},{id:'lima',name:'Lima',unit:'ud',quantity:28,min:12,price:.55}];
const nav=[['Resumen',LayoutDashboard],['Cócteles',GlassWater],['Ingredientes',Package],['Stock',ShoppingCart],['Carta digital',Wine],['Configuración',Settings]] as const;
export default function Home(){
 const[active,setActive]=useState('Resumen'),[query,setQuery]=useState(''),[recipes,setRecipes]=useState<Recipe[]>(seedRecipes),[ingredients,setIngredients]=useState<Ingredient[]>(seedIngredients),[modal,setModal]=useState<'recipe'|'ingredient'|'import'|null>(null),[editing,setEditing]=useState<Recipe|null>(null),[toast,setToast]=useState('');
 useEffect(()=>{const r=localStorage.getItem('baros-recipes'),i=localStorage.getItem('baros-ingredients');if(r)setRecipes(JSON.parse(r));if(i)setIngredients(JSON.parse(i))},[]);
 const saveR=(v:Recipe[])=>{setRecipes(v);localStorage.setItem('baros-recipes',JSON.stringify(v))},saveI=(v:Ingredient[])=>{setIngredients(v);localStorage.setItem('baros-ingredients',JSON.stringify(v))},notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const low=ingredients.filter(i=>i.quantity<=i.min),avg=recipes.length?Math.round(recipes.reduce((a,r)=>a+(1-r.cost/r.price)*100,0)/recipes.length):0,filtered=useMemo(()=>recipes.filter(r=>`${r.name} ${r.ingredients}`.toLowerCase().includes(query.toLowerCase())),[recipes,query]);
 const openNew=()=>{setEditing(null);setModal('recipe')};
 return <main className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">B</div><div><strong>BAROS</strong><span>cocktail OS</span></div></div><div className="venue"><div className="venue-avatar">LC</div><div><b>La Copa</b><span>Madrid · Local 01</span></div><ChevronRight size={15}/></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'nav active':'nav'} onClick={()=>setActive(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="help"><Sparkles size={16}/><span><b>Plan Starter</b><small>12 días restantes</small></span></div><button className="user"><div>VC</div><span><b>Mi cuenta</b><small>Administrador</small></span></button></div></aside>
 <section className="content"><header className="topbar"><div><p className="eyebrow">LUNES, 7 SEPTIEMBRE 2026</p><h1>{active}</h1></div><div className="top-actions"><button className="icon-btn"><Bell size={18}/><i/></button><button className="primary" onClick={openNew}><Plus size={17}/> Nuevo cóctel</button></div></header>
 {active==='Resumen'&&<><div className="hero"><div><span className="pill"><Sparkles size={14}/> BAROS INTELLIGENCE</span><h2>Tu carta, tus costes,<br/><em>bajo control.</em></h2><p>Gestiona recetas y stock. Descubre qué cócteles puedes preparar con lo que tienes.</p><div className="hero-actions"><button className="dark" onClick={()=>setActive('Cócteles')}><Search size={16}/> Buscar un cóctel</button><button className="ghost" onClick={()=>setModal('import')}>Importar desde TheCocktailDB <ChevronRight size={15}/></button></div></div><div className="hero-glass"><div className="liquid"/><div className="garnish"/><div className="ice i1"/><div className="ice i2"/><div className="ice i3"/></div></div><div className="metrics"><Metric icon={<CircleDollarSign/>} label="Ventas estimadas" value="2.840 €" delta="+12,4%"/><Metric icon={<TrendingUp/>} label="Margen medio" value={`${avg}%`} delta="calculado en tu carta"/><Metric icon={<GlassWater/>} label="Cócteles activos" value={String(recipes.length)} delta="guardados"/><Metric icon={<Package/>} label="Stock bajo" value={String(low.length)} delta={low.length?'Revisar ahora':'Todo correcto'} warning={!!low.length}/></div><section className="panel"><div className="panel-head"><div><h3>Tu carta</h3><p>Coste, precio y margen por cóctel.</p></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar..."/></div></div><RecipeTable rows={filtered} onEdit={r=>{setEditing(r);setModal('recipe')}}/></section><div className="bottom-grid"><StockPanel ingredients={low}/><section className="panel opportunity"><span className="pill"><Sparkles size={14}/> OPORTUNIDAD</span><h3>Te faltan {low.length} ingredientes<br/>para <em>ampliar tu carta.</em></h3><p>Optimiza tu próxima compra y amplía tu carta con el stock que ya tienes.</p><button className="dark" onClick={()=>setActive('Stock')}>Ver recomendaciones <ChevronRight size={15}/></button></section></div></>}
 {active==='Cócteles'&&<Cocktails recipes={recipes} query={query} setQuery={setQuery} onNew={openNew} onEdit={r=>{setEditing(r);setModal('recipe')}} onImport={()=>setModal('import')}/>} {active==='Ingredientes'&&<Ingredients ingredients={ingredients} onNew={()=>setModal('ingredient')} onSave={saveI}/>} {active==='Stock'&&<Stock ingredients={ingredients} onSave={saveI}/>} {active==='Carta digital'&&<Menu recipes={recipes}/>} {active==='Configuración'&&<SettingsPanel/>}<footer>BAROS · Gestión inteligente para bares <span>Beta privada</span></footer></section>
 {modal==='recipe'&&<RecipeModal initial={editing} onClose={()=>setModal(null)} onSave={r=>{saveR(editing?recipes.map(x=>x.id===r.id?r:x):[...recipes,r]);setModal(null);notify('Cóctel guardado')}}/>}{modal==='ingredient'&&<IngredientModal onClose={()=>setModal(null)} onSave={i=>{saveI([...ingredients,i]);setModal(null);notify('Ingrediente añadido')}}/>}{modal==='import'&&<ImportModal onClose={()=>setModal(null)} onImport={r=>{saveR([...recipes,r]);setModal(null);notify(`${r.name} importado`)}}/>}{toast&&<div className="toast">✓ {toast}</div>}</main>}
function Metric({icon,label,value,delta,warning=false}:{icon:React.ReactNode;label:string;value:string;delta:string;warning?:boolean}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><b>{value}</b><small className={warning?'warn':''}>{delta}</small></div></div>}
function RecipeTable({rows,onEdit}:{rows:Recipe[];onEdit:(r:Recipe)=>void}){return <div className="table">{rows.map(r=>{const m=Math.round((1-r.cost/r.price)*100);return <div className="row" key={r.id}><div className="cocktail"><div className="cocktail-icon">🍸</div><div><b>{r.name}</b><span>{r.ingredients}</span></div></div><span className="category">{r.category}</span><span>{r.cost.toFixed(2)} €</span><span>{r.price.toFixed(2)} €</span><strong>{m}%</strong><span className={r.stock==='Bajo'?'status low':'status'}>{r.stock}</span><button className="more" onClick={()=>onEdit(r)}>Editar</button></div>})}</div>}
function StockPanel({ingredients}:{ingredients:Ingredient[]}){return <section className="panel compact"><div className="panel-head"><div><h3>Stock por revisar</h3><p>Ingredientes cerca del mínimo.</p></div></div>{ingredients.slice(0,4).map(i=><div className="stock-row" key={i.id}><div className="stock-dot"/><div><b>{i.name}</b><span>Mín. {i.min} {i.unit}</span></div><strong>{i.quantity} {i.unit}</strong></div>)}</section>}
function Cocktails({recipes,query,setQuery,onNew,onEdit,onImport}:{recipes:Recipe[];query:string;setQuery:(s:string)=>void;onNew:()=>void;onEdit:(r:Recipe)=>void;onImport:()=>void}){const f=recipes.filter(r=>`${r.name} ${r.ingredients}`.toLowerCase().includes(query.toLowerCase()));return <section className="panel page-panel"><div className="section-actions"><div><h2 className="page-title">Cócteles</h2><p>Gestiona tu recetario y calcula el margen real de cada copa.</p></div><div><button className="ghost" onClick={onImport}>Importar TheCocktailDB</button><button className="primary inline" onClick={onNew}><Plus size={15}/> Nuevo cóctel</button></div></div><div className="search wide"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre o ingrediente..."/></div><RecipeTable rows={f} onEdit={onEdit}/></section>}
function Ingredients({ingredients,onNew,onSave}:{ingredients:Ingredient[];onNew:()=>void;onSave:(v:Ingredient[])=>void}){return <section className="panel page-panel"><div className="section-actions"><div><h2 className="page-title">Ingredientes</h2><p>Precios de compra y cantidades disponibles.</p></div><button className="primary inline" onClick={onNew}><Plus size={15}/> Añadir ingrediente</button></div><div className="ingredient-grid">{ingredients.map(i=><div className={i.quantity<=i.min?'ingredient-card low-card':'ingredient-card'} key={i.id}><div><b>{i.name}</b><span>{i.price.toFixed(2)} € / {i.unit}</span></div><strong>{i.quantity} {i.unit}</strong><small>{i.quantity<=i.min?'⚠ Stock bajo':'✓ Stock OK'}</small><input type="number" step="0.01" value={i.quantity} onChange={e=>onSave(ingredients.map(x=>x.id===i.id?{...x,quantity:Number(e.target.value)}:x))}/></div>)}</div></section>}
function Stock({ingredients,onSave}:{ingredients:Ingredient[];onSave:(v:Ingredient[])=>void}){return <section className="panel page-panel"><h2 className="page-title">Stock</h2><p>Actualiza cantidades y controla los mínimos de compra.</p><div className="stock-table">{ingredients.map(i=><div className="stock-line" key={i.id}><b>{i.name}</b><span>{i.unit}</span><input type="number" step="0.01" value={i.quantity} onChange={e=>onSave(ingredients.map(x=>x.id===i.id?{...x,quantity:Number(e.target.value)}:x))}/><span>Mín. {i.min}</span><strong className={i.quantity<=i.min?'stock-alert':'stock-good'}>{i.quantity<=i.min?'Comprar':'Correcto'}</strong></div>)}</div></section>}
function Menu({recipes}:{recipes:Recipe[]}){return <section className="panel page-panel digital"><span className="pill">CARTA DIGITAL</span><h2 className="page-title">La Copa</h2><p>Vista previa de la carta que podrás compartir mediante enlace o QR.</p><div className="menu-grid">{recipes.map(r=><div className="menu-card" key={r.id}><div className="menu-photo">🍸</div><h3>{r.name}</h3><span>{r.ingredients}</span><strong>{r.price.toFixed(2)} €</strong></div>)}</div></section>}
function SettingsPanel(){return <section className="panel page-panel"><h2 className="page-title">Configuración</h2><p>Preferencias de tu local.</p><div className="settings-list"><label>Nombre del local<input defaultValue="La Copa"/></label><label>Ciudad<input defaultValue="Madrid"/></label><label>Moneda<select defaultValue="EUR"><option>EUR · Euro</option><option>GBP · Libra</option><option>USD · Dólar</option></select></label></div></section>}
function RecipeModal({initial,onClose,onSave}:{initial:Recipe|null;onClose:()=>void;onSave:(r:Recipe)=>void}){const[name,setName]=useState(initial?.name||''),[cat,setCat]=useState(initial?.category||'Classic'),[cost,setCost]=useState(initial?.cost||1.5),[price,setPrice]=useState(initial?.price||9),[ings,setIngs]=useState(initial?.ingredients||'');return <Modal title={initial?'Editar cóctel':'Nuevo cóctel'} onClose={onClose}><label>Nombre<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Espresso Martini"/></label><label>Categoría<select value={cat} onChange={e=>setCat(e.target.value)}><option>Classic</option><option>Sour</option><option>Signature</option><option>Tiki</option></select></label><div className="form-grid"><label>Coste (€)<input type="number" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label>Precio venta (€)<input type="number" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label></div><label>Ingredientes<input value={ings} onChange={e=>setIngs(e.target.value)} placeholder="Gin · Lima · Vermut..."/></label><button className="primary save" onClick={()=>name.trim()&&onSave({id:initial?.id||crypto.randomUUID(),name:name.trim(),category:cat,cost,price,stock:'OK',ingredients:ings})}><Save size={15}/> Guardar cóctel</button></Modal>}
function IngredientModal({onClose,onSave}:{onClose:()=>void;onSave:(i:Ingredient)=>void}){const[name,setName]=useState(''),[unit,setUnit]=useState('L'),[price,setPrice]=useState(10),[min,setMin]=useState(1),[qty,setQty]=useState(1);return <Modal title="Nuevo ingrediente" onClose={onClose}><label>Nombre<input autoFocus value={name} onChange={e=>setName(e.target.value)}/></label><div className="form-grid"><label>Unidad<select value={unit} onChange={e=>setUnit(e.target.value)}><option>L</option><option>ml</option><option>g</option><option>ud</option></select></label><label>Precio compra<input type="number" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label></div><div className="form-grid"><label>Stock actual<input type="number" step="0.01" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Stock mínimo<input type="number" step="0.01" value={min} onChange={e=>setMin(Number(e.target.value))}/></label></div><button className="primary save" onClick={()=>name.trim()&&onSave({id:crypto.randomUUID(),name:name.trim(),unit,price,min,quantity:qty})}><Save size={15}/> Guardar ingrediente</button></Modal>}
function ImportModal({onClose,onImport}:{onClose:()=>void;onImport:(r:Recipe)=>void}){const[q,setQ]=useState('margarita'),[loading,setLoading]=useState(false),[results,setResults]=useState<any[]>([]);const search=async()=>{setLoading(true);try{const d=await fetch(`/api/cocktails?q=${encodeURIComponent(q)}`).then(r=>r.json());setResults(d.drinks||[])}finally{setLoading(false)}};useEffect(()=>{search()},[]);return <Modal title="Importar desde TheCocktailDB" onClose={onClose}><div className="search wide"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()}/><button className="dark" onClick={search}>{loading?'...':'Buscar'}</button></div><div className="import-results">{results.slice(0,8).map(d=><button key={d.idDrink} onClick={()=>onImport({id:crypto.randomUUID(),name:d.strDrink,category:d.strCategory||'Imported',cost:0,price:9,stock:'OK',ingredients:[d.strIngredient1,d.strIngredient2,d.strIngredient3,d.strIngredient4].filter(Boolean).join(' · ')})}><span>🍸</span><b>{d.strDrink}</b><small>{d.strCategory||'Cocktail'}</small><ChevronRight size={15}/></button>)}</div>{!loading&&!results.length&&<p className="empty">No encontramos resultados.</p>}</Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
